[tools]
node = "22.18.0"

[tasks.build-backend-linux-amd64]
description = "Build backend for linux amd64"
run = "cd backend && GOARCH=amd64 GOOS=linux go build -o dist/backend-linux-amd64 ./main.go"

[tasks.build-backend-linux-arm64]
description = "Build backend for linux arm64"
run = "cd backend && GOARCH=arm64 GOOS=linux go build -o dist/backend-linux-arm64 ./main.go"

[tasks.build-backend-windows-amd64]
description = "Build backend for windows amd64"
run = "cd backend && GOARCH=amd64 GOOS=windows go build -o dist/backend-windows-amd64 ./main.go"

[tasks.build-backend-windows-arm64]
description = "Build backend for windows arm64"
run = "cd backend && GOARCH=arm64 GOOS=windows go build -o dist/backend-windows-arm64 ./main.go"

[tasks.build-backend-darwin-amd64]
description = "Build backend for darwin amd64"
run = "cd backend && GOARCH=amd64 GOOS=darwin go build -o dist/backend-darwin-amd64 ./main.go"

[tasks.build-backend-darwin-arm64]
description = "Build backend for darwin arm64"
run = "cd backend && GOARCH=arm64 GOOS=darwin go build -o dist/backend-darwin-arm64 ./main.go"